const { URL } = require('url');

const CATEGORY_RULES = [
  { category: 'E-Commerce', patterns: [/amazon\./i, /flipkart\./i, /shopify\./i, /ebay\./i, /myntra\./i] },
  { category: 'Entertainment', patterns: [/youtube\./i, /netflix\./i, /spotify\./i, /twitch\./i] },
  { category: 'Social Media', patterns: [/facebook\./i, /instagram\./i, /twitter\./i, /x\.com/i, /tiktok\./i] },
  { category: 'Professional', patterns: [/linkedin\./i, /indeed\./i, /glassdoor\./i] },
  { category: 'Development', patterns: [/github\./i, /gitlab\./i, /stackoverflow\./i, /npmjs\./i] },
  { category: 'Education', patterns: [/coursera\./i, /udemy\./i, /khanacademy\./i, /\.edu\b/i] },
];

const SUSPICIOUS_PATTERNS = [
  /bit\.ly\/malware/i,
  /login-verify/i,
  /secure-update/i,
  /free-iphone/i,
  /\.zip$/i,
  /password-reset-now/i,
];

const SUSPICIOUS_TLDS = ['.xyz', '.top', '.click', '.loan', '.work'];

function detectCategory(urlString) {
  try {
    const host = new URL(urlString).hostname;
    for (const rule of CATEGORY_RULES) {
      if (rule.patterns.some((p) => p.test(host) || p.test(urlString))) return rule.category;
    }
    if (/news|blog|medium/i.test(host)) return 'Media';
    return 'Others';
  } catch {
    return 'Others';
  }
}

function checkThreat(urlString) {
  try {
    const parsed = new URL(urlString);
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
      return { level: 'blocked', message: 'Unsupported URL protocol' };
    }
    if (/^\d+\.\d+\.\d+\.\d+$/.test(parsed.hostname)) {
      return { level: 'warning', message: 'This URL uses a raw IP address and may be unsafe.' };
    }
    if (SUSPICIOUS_TLDS.some((tld) => parsed.hostname.endsWith(tld))) {
      return { level: 'warning', message: 'This domain uses a high-risk TLD pattern.' };
    }
    if (SUSPICIOUS_PATTERNS.some((p) => p.test(urlString))) {
      return { level: 'warning', message: 'This URL appears unsafe (phishing/malware pattern detected).' };
    }
    if (/login|verify|account|bank|wallet/i.test(urlString) && !/google|microsoft|github|amazon/i.test(parsed.hostname)) {
      return { level: 'warning', message: 'This URL contains sensitive keywords and may be a phishing attempt.' };
    }
    return { level: 'safe', message: 'No immediate threats detected.' };
  } catch {
    return { level: 'blocked', message: 'Invalid URL format' };
  }
}

async function fetchUrlPreview(urlString) {
  const fallback = { title: '', description: '', image: '', favicon: '' };
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 5000);
    const res = await fetch(urlString, {
      signal: controller.signal,
      headers: { 'User-Agent': 'LinkLensBot/1.0' },
      redirect: 'follow',
    });
    clearTimeout(timeout);
    const html = await res.text();
    const title = (html.match(/<title[^>]*>([^<]*)<\/title>/i) || [])[1]?.trim() || '';
    const description =
      (html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']+)["']/i) || [])[1] ||
      (html.match(/<meta[^>]+property=["']og:description["'][^>]+content=["']([^"']+)["']/i) || [])[1] ||
      '';
    const image =
      (html.match(/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)["']/i) || [])[1] || '';
    const host = new URL(urlString).origin;
    return {
      title: title || host,
      description: description || 'Preview generated by LinkLens AI',
      image,
      favicon: `${host}/favicon.ico`,
    };
  } catch {
    try {
      const host = new URL(urlString).hostname;
      return { ...fallback, title: host, description: `Smart preview for ${host}` };
    } catch {
      return fallback;
    }
  }
}

function generateAiInsights(link, visits, trend) {
  const insights = [];
  const mobile = visits.filter((v) => v.device === 'Mobile').length;
  const mobilePct = visits.length ? Math.round((mobile / visits.length) * 100) : 0;

  if (trend.growthPercent > 0) {
    insights.push(`Your link "${link.shortCode}" gained ${trend.growthPercent}% more traffic this week.`);
  } else {
    insights.push(`Your link "${link.shortCode}" is ready for promotion — start sharing to unlock growth.`);
  }

  if (mobilePct >= 50) insights.push(`Most visitors (${mobilePct}%) came from mobile devices.`);
  else insights.push('Desktop traffic is significant — optimize landing pages for larger screens.');

  if (trend.peakHour) insights.push(`Peak traffic window: ${trend.peakHour}.`);
  if (link.category && link.category !== 'Others') insights.push(`AI classified this URL as ${link.category}.`);

  return insights;
}

function computePerformanceScore(link, visits, trend) {
  const recencyBoost = link.lastVisitedAt ? 15 : 0;
  const growthBoost = Math.min(35, Math.max(0, trend.growthPercent));
  const engagementBoost = Math.min(35, Math.floor((link.clickCount || 0) / 30));
  const score = Math.min(100, 10 + recencyBoost + growthBoost + engagementBoost);
  let engagement = 'Low';
  if (score >= 75) engagement = 'High';
  else if (score >= 45) engagement = 'Medium';
  return { score, growth: trend.growthPercent, engagement };
}

function getBadges(clickCount) {
  const badges = [];
  if (clickCount >= 100) badges.push({ id: 'bronze', label: '100 Clicks', icon: '🥉' });
  if (clickCount >= 1000) badges.push({ id: 'silver', label: '1000 Clicks', icon: '🥈' });
  if (clickCount >= 10000) badges.push({ id: 'gold', label: '10000 Clicks', icon: '🥇' });
  if (clickCount >= 5000) badges.push({ id: 'viral', label: 'Viral Link', icon: '🚀' });
  return badges;
}

module.exports = {
  detectCategory,
  checkThreat,
  fetchUrlPreview,
  generateAiInsights,
  computePerformanceScore,
  getBadges,
  CATEGORY_RULES,
};
